name: pre-commit

on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.22
            - name: Install goimports
              run: go install golang.org/x/tools/cmd/goimports@latest
            - name: Install gocyclo
              run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

            - uses: pre-commit/action@v3.0.0
